"use client";

import { useMemo, useState } from "react";
import styles from "./ForexCalculator.module.css";

type Tool = "position" | "pnl" | "pip" | "margin" | "compound" | "risk" | "drawdown" | "swap";
type SymbolInfo = { symbol: string; contract: number; pip: number; price: number; pipLot: number };
const SYMBOLS: SymbolInfo[] = [
  { symbol: "EUR/USD", contract: 100000, pip: .0001, price: 1.17, pipLot: 10 },
  { symbol: "GBP/USD", contract: 100000, pip: .0001, price: 1.35, pipLot: 10 },
  { symbol: "USD/JPY", contract: 100000, pip: .01, price: 155, pipLot: 6.45 },
  { symbol: "USD/CHF", contract: 100000, pip: .0001, price: .8, pipLot: 12.5 },
  { symbol: "AUD/USD", contract: 100000, pip: .0001, price: .66, pipLot: 10 },
  { symbol: "USD/CAD", contract: 100000, pip: .0001, price: 1.38, pipLot: 7.25 },
  { symbol: "XAU/USD", contract: 100, pip: .01, price: 3400, pipLot: 1 },
  { symbol: "BTC/USD", contract: 1, pip: 1, price: 110000, pipLot: 1 },
];

const COPY = {
  en: { title:"Forex Calculator", eyebrow:"ROCO TRADING TOOLS", lead:"Plan the trade before you place it.", intro:"Six practical calculators help you size exposure and test outcomes. Results update instantly as you type.", disclaimer:"Indicative results only. Prices and contract specifications vary by broker and market conditions.", calculate:"Live result", symbol:"Trading symbol", balance:"Account balance (USD)", riskPct:"Risk (%)", stop:"Stop loss (pips)", lots:"Trade size (lots)", side:"Position", buy:"Buy", sell:"Sell", entry:"Entry price", exit:"Exit price", leverage:"Leverage", principal:"Starting balance", periods:"Number of periods", returnPct:"Return per period (%)", reinvest:"Profit reinvested (%)", target:"Take profit", current:"Current balance", initial:"Initial balance", swapRate:"Swap rate (points/night)", nights:"Nights held", result:"Calculation result", riskAmount:"Amount at risk", standardLots:"Standard lots", miniLots:"Mini lots", microLots:"Micro lots", profitLoss:"Estimated P/L", pipValue:"Pip value", requiredMargin:"Required margin", finalBalance:"Final balance", totalReturn:"Total return", ratio:"Risk : reward", breakeven:"Break-even win rate", drawdown:"Drawdown", recovery:"Gain needed to recover", swapTotal:"Estimated swap", position:"Position size", pnl:"Profit / Loss", pip:"Pip value", margin:"Margin", compound:"Compound growth", risk:"Risk : Reward", drawdownTab:"Drawdown", swap:"Swap", soon:"Temporarily unavailable", inputTitle:"Trade details", inputHint:"Enter your planned trade values", tutorial:"Complete calculator guide", tutorialIntro:"Learn what each result means, follow a worked example and avoid common sizing mistakes.", step:"Step", formula:"Formula", purpose:"What this calculator tells you", example:"Worked example", interpretation:"How to read the result", practicalNote:"Practical note" },
  fa: { title:"ماشین حساب فارکس", eyebrow:"ابزارهای معاملاتی روکو", lead:"پیش از ورود، معامله را دقیق برنامه‌ریزی کنید.", intro:"شش ماشین حساب کاربردی برای مدیریت حجم و بررسی نتیجه معامله. با تغییر هر مقدار، نتیجه همان لحظه به‌روز می‌شود.", disclaimer:"نتایج تقریبی‌اند. قیمت و مشخصات قرارداد ممکن است بر اساس بروکر و شرایط بازار تغییر کند.", calculate:"نتیجه لحظه‌ای", symbol:"نماد معاملاتی", balance:"موجودی حساب (دلار)", riskPct:"درصد ریسک", stop:"حد ضرر (پیپ)", lots:"حجم معامله (لات)", side:"نوع معامله", buy:"خرید", sell:"فروش", entry:"قیمت ورود", exit:"قیمت خروج", leverage:"اهرم", principal:"سرمایه اولیه", periods:"تعداد دوره", returnPct:"سود هر دوره (%)", reinvest:"درصد بازسرمایه‌گذاری", target:"حد سود", current:"موجودی فعلی", initial:"موجودی اولیه", swapRate:"نرخ سواپ (پوینت/شب)", nights:"تعداد شب", result:"نتیجه محاسبه", riskAmount:"مبلغ ریسک", standardLots:"لات استاندارد", miniLots:"مینی لات", microLots:"میکرو لات", profitLoss:"سود / زیان تقریبی", pipValue:"ارزش هر پیپ", requiredMargin:"مارجین مورد نیاز", finalBalance:"موجودی نهایی", totalReturn:"سود کل", ratio:"ریسک به ریوارد", breakeven:"وین‌ریت سربه‌سر", drawdown:"افت سرمایه", recovery:"سود لازم برای جبران", swapTotal:"سواپ تقریبی", position:"حجم معامله", pnl:"سود / زیان", pip:"ارزش پیپ", margin:"مارجین", compound:"سود مرکب", risk:"ریسک : ریوارد", drawdownTab:"دراداون", swap:"سواپ", soon:"موقتاً غیرفعال", inputTitle:"جزئیات معامله", inputHint:"مقادیر معامله مورد نظر را وارد کنید", tutorial:"راهنمای جامع ماشین حساب", tutorialIntro:"کاربرد هر نتیجه، یک مثال واقعی و خطاهای رایج مدیریت سرمایه را یاد بگیرید.", step:"مرحله", formula:"فرمول", purpose:"این ماشین حساب چه چیزی نشان می‌دهد؟", example:"مثال عملی", interpretation:"چگونه نتیجه را بخوانیم؟", practicalNote:"نکته کاربردی" },
} as const;

const TOOLS: { id: Tool; key: keyof typeof COPY.en; disabled?: boolean }[] = [
  {id:"position",key:"position"},{id:"pnl",key:"pnl"},{id:"pip",key:"pip"},{id:"margin",key:"margin"},
  {id:"compound",key:"compound"},{id:"risk",key:"risk"},{id:"drawdown",key:"drawdownTab"},{id:"swap",key:"swap",disabled:true},
];

function ToolIcon({id}:{id:Tool}) {
  const paths:Record<Tool,React.ReactNode>={
    position:<><circle cx="12" cy="12" r="7"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></>,
    pnl:<><path d="M4 18 10 12l4 3 6-8"/><path d="M15 7h5v5"/></>, pip:<><path d="M12 3 21 12 12 21 3 12Z"/><path d="M9 12h6"/></>,
    margin:<><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/></>, compound:<><path d="M4 18c3-8 6-8 8-3s5 4 8-6"/><path d="m17 8 3 1-1 3"/></>,
    risk:<><path d="M4 8h12M13 5l3 3-3 3M20 16H8M11 13l-3 3 3 3"/></>, drawdown:<><path d="M4 6l6 6 4-4 6 6"/><path d="M20 10v4h-4"/></>,
    swap:<><path d="M7 7h11l-3-3M17 17H6l3 3"/><circle cx="6" cy="7" r="2"/><circle cx="18" cy="17" r="2"/></>,
  };
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[id]}</svg>;
}
const n = (v: string) => Number(v) || 0;
const money = (v: number) => new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:2 }).format(Number.isFinite(v) ? v : 0);
const num = (v: number, digits=2) => new Intl.NumberFormat("en-US", { maximumFractionDigits:digits }).format(Number.isFinite(v) ? v : 0);

function Input({label, value, onChange, step="any"}:{label:string;value:string;onChange:(v:string)=>void;step?:string}) {
  return <label className={styles.field}><span>{label}</span><input type="number" inputMode="decimal" step={step} value={value} onChange={e=>onChange(e.target.value)} /></label>;
}

export function ForexCalculator({ locale }: { locale: string }) {
  const t = locale === "fa" ? COPY.fa : COPY.en;
  const [tool,setTool]=useState<Tool>("position"), [symbol,setSymbol]=useState("EUR/USD"), [balance,setBalance]=useState("10000"), [riskPct,setRiskPct]=useState("1"), [stop,setStop]=useState("50"), [stopPrice,setStopPrice]=useState("1.1600"), [lots,setLots]=useState("1"), [side,setSide]=useState("buy"), [entry,setEntry]=useState("1.1700"), [exit,setExit]=useState("1.1800"), [leverage,setLeverage]=useState("100"), [principal,setPrincipal]=useState("1000"), [periods,setPeriods]=useState("12"), [returnPct,setReturnPct]=useState("5"), [reinvest,setReinvest]=useState("100"), [target,setTarget]=useState("1.1900"), [initial,setInitial]=useState("10000"), [current,setCurrent]=useState("8000"), [swapRate,setSwapRate]=useState("-3.5"), [nights,setNights]=useState("3");
  const info=SYMBOLS.find(s=>s.symbol===symbol) ?? SYMBOLS[0];
  const guides:Record<Exclude<Tool,"swap">,{steps:string[];formula:string}> = locale === "fa" ? {
    position:{steps:["نماد معاملاتی را انتخاب کنید.","موجودی حساب و درصدی که حاضر به ریسک هستید وارد کنید.","فاصله حد ضرر را به پیپ بنویسید و حجم پیشنهادی را ببینید."],formula:"حجم = مبلغ ریسک ÷ (حد ضرر به پیپ × ارزش هر پیپ)"},
    pnl:{steps:["نماد و جهت خرید یا فروش را مشخص کنید.","حجم و قیمت ورود معامله را وارد کنید.","قیمت خروج احتمالی را وارد و سود یا زیان را بررسی کنید."],formula:"سود/زیان = اختلاف قیمت × اندازه قرارداد × حجم معامله"},
    pip:{steps:["نماد معاملاتی را انتخاب کنید.","حجم مورد نظر را به لات وارد کنید.","نتیجه نشان می‌دهد حرکت یک پیپ چه اثری بر حساب دارد."],formula:"ارزش پیپ = ارزش پیپ یک لات × حجم معامله"},
    margin:{steps:["نماد معاملاتی و در نتیجه اندازه قرارداد و قیمت بازار را مشخص کنید.","حجم معامله را به لات وارد کنید.","اهرم حساب را وارد و وجه تضمین تقریبی مورد نیاز را بررسی کنید."],formula:"مارجین = اندازه قرارداد × حجم لات × قیمت بازار ÷ اهرم"},
    compound:{steps:["سرمایه شروع را وارد کنید.","بازده مورد انتظار و تعداد دوره‌ها را تعیین کنید.","درصد سودی را که دوباره سرمایه‌گذاری می‌شود تنظیم کنید."],formula:"موجودی نهایی = سرمایه × (۱ + نرخ مؤثر) به توان تعداد دوره"},
    risk:{steps:["قیمت ورود برنامه‌ریزی‌شده را وارد کنید.","قیمت حد ضرر و حد سود را مشخص کنید.","نسبت بالاتر یعنی پاداش احتمالی بیشتری در برابر هر واحد ریسک."],formula:"ریوارد ÷ ریسک = فاصله هدف از ورود ÷ فاصله حد ضرر از ورود"},
    drawdown:{steps:["بیشترین یا موجودی اولیه حساب را وارد کنید.","موجودی فعلی را وارد کنید.","درصد افت و سود لازم برای بازگشت را با هم بررسی کنید."],formula:"دراداون = (موجودی اولیه − فعلی) ÷ موجودی اولیه × ۱۰۰"},
  } : {
    position:{steps:["Choose the instrument you plan to trade.","Enter your account balance and acceptable risk percentage.","Add the stop-loss distance in pips and review the suggested lot size."],formula:"Position size = risk amount ÷ (stop-loss pips × pip value)"},
    pnl:{steps:["Choose the instrument and Buy or Sell direction.","Enter the trade size and planned entry price.","Add a possible exit price to estimate the outcome."],formula:"P/L = price difference × contract size × trade volume"},
    pip:{steps:["Choose the trading instrument.","Enter your planned volume in lots.","The result shows the account impact of a one-pip move."],formula:"Pip value = one-lot pip value × trade volume"},
    margin:{steps:["Choose the instrument, which supplies its contract size and market price.","Enter the planned trade volume in lots.","Enter the account leverage and review the estimated margin requirement."],formula:"Margin = contract size × lot size × market price ÷ leverage"},
    compound:{steps:["Enter the starting balance.","Set the expected return and number of periods.","Choose how much profit is reinvested each period."],formula:"Final balance = principal × (1 + effective rate)ⁿ"},
    risk:{steps:["Enter the planned entry price.","Set the stop-loss and take-profit prices.","Compare potential reward with each unit of risk and the break-even win rate."],formula:"Reward ÷ risk = target distance ÷ stop-loss distance"},
    drawdown:{steps:["Enter the account's initial or peak balance.","Enter its current balance.","Review both the loss and the larger gain needed to recover."],formula:"Drawdown = (initial − current) ÷ initial × 100"},
  };
  const details:Record<Exclude<Tool,"swap">,{purpose:string;example:string;interpretation:string;note:string}> = locale === "fa" ? {
    position:{purpose:"حجم معامله مشخص می‌کند با توجه به موجودی، درصد ریسک و فاصله حد ضرر، حداکثر چند لات می‌توانید وارد معامله شوید. هدف این ابزار ثابت نگه‌داشتن ریسک دلاری است؛ نه بزرگ‌کردن حجم برای رسیدن به سود بیشتر.",example:"فرض کنید موجودی شما ۱۰٬۰۰۰ دلار، ریسک مجاز ۱٪ و حد ضرر ۵۰ پیپ است. مبلغ ریسک ۱۰۰ دلار می‌شود. اگر ارزش هر پیپ یک لات EUR/USD برابر ۱۰ دلار باشد، حجم پیشنهادی ۰٫۲۰ لات است: ۱۰۰ ÷ (۵۰ × ۱۰).",interpretation:"لات استاندارد همان عددی است که معمولاً در متاتریدر وارد می‌کنید. یک مینی‌لات برابر ۰٫۱ لات و یک میکرولات برابر ۰٫۰۱ لات است. اگر حجم پیشنهادی بین دو گام مجاز قرار گرفت، برای حفظ سقف ریسک آن را رو به پایین گرد کنید.",note:"حد ضرر را بر اساس ساختار بازار تعیین کنید و سپس حجم را محاسبه کنید. جابه‌جا کردن حد ضرر فقط برای افزایش حجم، منطق مدیریت ریسک را از بین می‌برد."},
    pnl:{purpose:"پیش از ثبت سفارش تخمین می‌زند اگر قیمت از نقطه ورود به خروج فرضی برسد، نتیجه مالی معامله چقدر خواهد بود. جهت خرید یا فروش در علامت نتیجه اثر مستقیم دارد.",example:"در خرید ۰٫۵ لات EUR/USD از ۱٫۱۷۰۰ تا ۱٫۱۸۰۰، حرکت قیمت ۱۰۰ پیپ است. با ارزش تقریبی ۵ دلار برای هر پیپ، سود ناخالص حدود ۵۰۰ دلار خواهد بود. در معامله فروش با همین حرکت، نتیجه منفی می‌شود.",interpretation:"عدد مثبت سود و عدد منفی زیان برآوردی است. این خروجی ناخالص است و ممکن است اسپرد، کمیسیون، اسلیپیج، تبدیل ارز حساب یا هزینه نگهداری شبانه را شامل نشود.",note:"برای سناریوی حد سود و حد ضرر جداگانه محاسبه کنید و هر دو عدد را پیش از ورود کنار هم ببینید؛ تنها بررسی سناریوی سود تصویری ناقص می‌دهد."},
    pip:{purpose:"ارزش پیپ نشان می‌دهد کوچک‌ترین واحد متداول حرکت قیمت برای حجم انتخابی چند واحد از ارز حساب شما ارزش دارد. این عدد حلقه اتصال فاصله حد ضرر و ریسک واقعی است.",example:"در EUR/USD، ارزش تقریبی هر پیپ برای یک لات استاندارد ۱۰ دلار است. بنابراین برای ۰٫۲۵ لات، هر پیپ حدود ۲٫۵۰ دلار و یک حرکت ۴۰ پیپی حدود ۱۰۰ دلار تغییر ایجاد می‌کند.",interpretation:"ارزش پیپ با تغییر حجم به همان نسبت تغییر می‌کند. در جفت‌هایی که دلار ارز مظنه نیست، ارزش پیپ با نرخ تبدیل بازار تغییر می‌کند؛ بنابراین عدد نمایش‌داده‌شده تقریبی است.",note:"پیپ را با پوینت اشتباه نگیرید. در بسیاری از نمادهای پنج‌رقمی، هر پیپ برابر ۱۰ پوینت است. مشخصات دقیق نماد را در پلتفرم معاملاتی بررسی کنید."},
    margin:{purpose:"مارجین مقدار وجه تضمینی است که برای باز کردن یک معامله کنار گذاشته می‌شود. این مقدار هزینه معامله نیست، اما تا زمان باز بودن پوزیشن بخشی از سرمایه آزاد حساب را درگیر می‌کند.",example:"اگر اندازه قرارداد ۱۰۰٬۰۰۰، حجم ۰٫۱۰ لات، قیمت بازار ۱٫۱۷ و اهرم ۱:۱۰۰ باشد، مارجین تقریبی برابر ۱۱۷ دلار است: ۱۰۰٬۰۰۰ × ۰٫۱۰ × ۱٫۱۷ ÷ ۱۰۰.",interpretation:"اهرم بیشتر مارجین مورد نیاز را کاهش می‌دهد، اما اندازه سود یا زیان ناشی از حرکت قیمت را کاهش نمی‌دهد. چند پوزیشن هم‌زمان می‌توانند مجموع مارجین مصرف‌شده را به‌سرعت افزایش دهند.",note:"این محاسبه از فرمول درخواستی و قیمت تقریبی داخلی استفاده می‌کند. تبدیل ارز حساب، نرخ مارجین ویژه نماد، حساب‌های هج‌شده و مشخصات واقعی سرور ممکن است نتیجه پلتفرم را تغییر دهند."},
    compound:{purpose:"رشد احتمالی سرمایه را در حالتی شبیه‌سازی می‌کند که بخشی یا تمام سود هر دوره دوباره وارد سرمایه شود. این ابزار برای برنامه‌ریزی است، نه پیش‌بینی بازده قطعی.",example:"سرمایه ۱٬۰۰۰ دلار با بازده فرضی ۵٪ در هر ماه و بازسرمایه‌گذاری کامل، پس از ۱۲ دوره تقریباً به ۱٬۷۹۵٫۸۶ دلار می‌رسد. سود هر دوره روی موجودی بزرگ‌تر دوره قبل محاسبه می‌شود.",interpretation:"موجودی نهایی شامل اصل سرمایه و سود ترکیبی است. کاهش درصد بازسرمایه‌گذاری، نرخ مؤثر رشد را کم می‌کند. بازده‌های منفی یا نامنظم در معامله واقعی می‌توانند مسیر کاملاً متفاوتی بسازند.",note:"از نرخ‌های محافظه‌کارانه استفاده کنید و سناریوهای ضعیف، متوسط و قوی را جداگانه بسنجید. سود ثابت در همه دوره‌ها یک فرض آموزشی است."},
    risk:{purpose:"فاصله حد سود را با فاصله حد ضرر مقایسه می‌کند و حداقل نرخ برد نظری برای سربه‌سر شدن را نشان می‌دهد. این نسبت کیفیت تحلیل یا احتمال رسیدن قیمت به هدف را اندازه نمی‌گیرد.",example:"ورود در ۱٫۱۷۰۰، حد ضرر ۱٫۱۶۰۰ و هدف ۱٫۱۹۰۰ یعنی ۰٫۰۱ ریسک در برابر ۰٫۰۲ پاداش؛ نسبت ۱ به ۲ و نرخ برد سربه‌سر نظری حدود ۳۳٫۳٪ است.",interpretation:"نسبت ۱:۲ یعنی در برابر هر یک واحد زیان احتمالی، دو واحد سود احتمالی دارید. نرخ سربه‌سر هزینه‌هایی مانند اسپرد و کمیسیون را نادیده می‌گیرد؛ نرخ برد واقعی لازم کمی بالاتر است.",note:"یک نسبت بزرگ به‌تنهایی معامله را خوب نمی‌کند. هدف و حد ضرر باید با ساختار بازار، نوسان و استراتژی شما سازگار باشند."},
    drawdown:{purpose:"میزان افت حساب از موجودی اولیه یا اوج و درصد رشد لازم برای بازگشت را محاسبه می‌کند. درصد جبران همیشه از درصد افت بزرگ‌تر است، زیرا رشد از پایه کوچک‌تری آغاز می‌شود.",example:"افت حساب از ۱۰٬۰۰۰ به ۸٬۰۰۰ دلار برابر ۲۰٪ است؛ اما برای بازگشت از ۸٬۰۰۰ به ۱۰٬۰۰۰ به ۲۵٪ سود نیاز دارید. افت ۵۰٪ برای جبران به ۱۰۰٪ رشد نیاز دارد.",interpretation:"دراداون شدت کاهش سرمایه را نشان می‌دهد و سود لازم برای جبران، دشواری بازسازی حساب را روشن می‌کند. بهتر است اوج اکویتی را نیز بررسی کنید، نه فقط بالانس بسته‌شده.",note:"پس از افت سنگین، برای جبران سریع حجم را افزایش ندهید. کاهش ریسک هر معامله و بازبینی استراتژی معمولاً از معامله انتقامی منطقی‌تر است."},
  } : {
    position:{purpose:"Position sizing converts your account balance, risk limit and stop-loss distance into a maximum trade volume. Its job is to keep the cash risk controlled—not to maximize potential profit.",example:"With a $10,000 balance, 1% risk and a 50-pip stop, the risk budget is $100. If one EUR/USD lot is worth about $10 per pip, the suggested size is 0.20 lots: 100 ÷ (50 × 10).",interpretation:"Standard lots are the volume normally entered in MetaTrader. One mini lot is 0.10 lots and one micro lot is 0.01 lots. When the result falls between permitted volume steps, round down to remain below your risk cap.",note:"Choose a technically valid stop first, then calculate volume. Moving a stop simply to obtain a larger position defeats the purpose of risk management."},
    pnl:{purpose:"This estimates the financial outcome if price moves from your entry to a hypothetical exit. Buy and Sell positions reverse the direction in which a price move produces profit.",example:"Buying 0.50 lots of EUR/USD at 1.1700 and exiting at 1.1800 is a 100-pip move. At roughly $5 per pip for that volume, the gross estimated profit is $500. The same movement is a loss for a Sell.",interpretation:"A positive number is estimated profit and a negative number is estimated loss. It is a gross result and may exclude spread, commission, slippage, account-currency conversion and overnight costs.",note:"Calculate the take-profit and stop-loss scenarios separately before entry. Looking only at the profitable outcome creates an incomplete trade plan."},
    pip:{purpose:"Pip value expresses what one standard unit of price movement is worth at your selected volume. It connects a stop distance measured in pips to actual account risk.",example:"One EUR/USD pip is approximately $10 for one standard lot. At 0.25 lots it is about $2.50, so a 40-pip move changes the position value by approximately $100.",interpretation:"Pip value changes in direct proportion to volume. For pairs whose quote currency differs from the account currency, it also moves with the relevant conversion rate, making static results indicative.",note:"Do not confuse a pip with a point. On many five-digit FX quotes, one pip equals ten points. Confirm the instrument specification in your trading platform."},
    margin:{purpose:"Margin is the collateral set aside to open a leveraged trade. It is not a transaction fee, but it reduces the account's free margin while the position remains open.",example:"With a 100,000 contract size, 0.10 lots, a 1.17 market price and 1:100 leverage, estimated margin is $117: 100,000 × 0.10 × 1.17 ÷ 100.",interpretation:"Higher leverage reduces required margin, but it does not reduce the profit or loss caused by price movement. Several simultaneous positions can quickly increase total used margin.",note:"This estimate uses the requested formula and an embedded indicative price. Account-currency conversion, symbol-specific margin rates, hedged positions and live server specifications can change the platform result."},
    compound:{purpose:"Compound growth models what may happen when some or all profit from each period is added to the next period's starting capital. It is a planning illustration, not a return forecast.",example:"A $1,000 starting balance earning a hypothetical 5% per month with full reinvestment grows to about $1,795.86 after 12 periods. Each period's return is calculated on the larger prior balance.",interpretation:"Final balance includes principal and compounded profit. Lower reinvestment reduces the effective growth rate. Real trading losses and variable returns can create a substantially different path.",note:"Use conservative assumptions and compare weak, average and strong scenarios. A constant positive return every period is an educational simplification."},
    risk:{purpose:"Risk/reward compares the distance to the target with the distance to the stop and derives the theoretical win rate needed to break even. It does not measure setup quality or target probability.",example:"Entry at 1.1700, stop at 1.1600 and target at 1.1900 means 0.01 risk against 0.02 reward: a 1:2 ratio with a theoretical break-even win rate of about 33.3%.",interpretation:"A 1:2 result means two units of potential reward for every unit at risk. The break-even rate excludes spread and commission, so the required real-world win rate will be slightly higher.",note:"A large ratio alone does not make a good trade. Both target and stop must remain realistic for the market structure, volatility and strategy."},
    drawdown:{purpose:"Drawdown measures the account decline from an initial or peak balance and the gain required to return. Recovery is always larger than the loss percentage because it starts from a smaller base.",example:"A decline from $10,000 to $8,000 is a 20% drawdown, but recovering from $8,000 to $10,000 requires a 25% gain. A 50% loss requires a 100% gain to recover.",interpretation:"Drawdown describes the severity of capital decline, while recovery highlights how difficult rebuilding becomes. Consider peak equity as well as closed account balance.",note:"Do not increase size to force a quick recovery after a deep drawdown. Reducing per-trade risk and reviewing the strategy is generally more controlled than revenge trading."},
  };
  const output=useMemo(()=>{
    const riskCash=n(balance)*n(riskPct)/100, size=riskCash/(Math.max(n(stop),.000001)*info.pipLot), signed=side==="buy"?1:-1;
    const pnl=(n(exit)-n(entry))*signed*info.contract*n(lots), pv=info.pipLot*n(lots), margin=info.contract*n(lots)*info.price/Math.max(n(leverage),1);
    const effective=n(returnPct)/100*n(reinvest)/100, final=n(principal)*Math.pow(1+effective,n(periods)), r=Math.abs(n(entry)-n(stopPrice)), reward=Math.abs(n(target)-n(entry)), ratio=r?reward/r:0;
    const dd=n(initial)>0?Math.max(0,(n(initial)-n(current))/n(initial)*100):0, recovery=n(current)>0?Math.max(0,(n(initial)-n(current))/n(current)*100):0, swap= n(swapRate)*n(lots)*n(nights)*info.pipLot/10;
    return {riskCash,size,pnl,pv,margin,final,total:final-n(principal),ratio,breakeven:ratio?100/(ratio+1):0,dd,recovery,swap};
  },[balance,riskPct,stop,stopPrice,lots,side,entry,exit,leverage,principal,periods,returnPct,reinvest,target,initial,current,swapRate,nights,info]);
  const symbolField=<label className={styles.field}><span>{t.symbol}</span><select value={symbol} onChange={e=>{setSymbol(e.target.value);const s=SYMBOLS.find(x=>x.symbol===e.target.value);if(s)setEntry(String(s.price));}}>{SYMBOLS.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></label>;
  let fields:React.ReactNode, results:[string,string][];
  if(tool==="position"){fields=<>{symbolField}<Input label={t.balance} value={balance} onChange={setBalance}/><Input label={t.riskPct} value={riskPct} onChange={setRiskPct}/><Input label={t.stop} value={stop} onChange={setStop}/></>;results=[[t.riskAmount,money(output.riskCash)],[t.standardLots,num(output.size,3)],[t.miniLots,num(output.size*10,2)],[t.microLots,num(output.size*100,1)]]}
  else if(tool==="pnl"){fields=<>{symbolField}<label className={styles.field}><span>{t.side}</span><select value={side} onChange={e=>setSide(e.target.value)}><option value="buy">{t.buy}</option><option value="sell">{t.sell}</option></select></label><Input label={t.lots} value={lots} onChange={setLots}/><Input label={t.entry} value={entry} onChange={setEntry}/><Input label={t.exit} value={exit} onChange={setExit}/></>;results=[[t.profitLoss,money(output.pnl)],[t.pipValue,money(output.pv)]]}
  else if(tool==="pip"){fields=<>{symbolField}<Input label={t.lots} value={lots} onChange={setLots}/></>;results=[[t.pipValue,money(output.pv)]]}
  else if(tool==="margin"){fields=<>{symbolField}<Input label={t.lots} value={lots} onChange={setLots}/><Input label={t.leverage} value={leverage} onChange={setLeverage}/></>;results=[[t.requiredMargin,money(output.margin)]]}
  else if(tool==="compound"){fields=<><Input label={t.principal} value={principal} onChange={setPrincipal}/><Input label={t.periods} value={periods} onChange={setPeriods}/><Input label={t.returnPct} value={returnPct} onChange={setReturnPct}/><Input label={t.reinvest} value={reinvest} onChange={setReinvest}/></>;results=[[t.finalBalance,money(output.final)],[t.totalReturn,money(output.total)]]}
  else if(tool==="risk"){fields=<><Input label={t.entry} value={entry} onChange={setEntry}/><Input label={t.stop} value={stopPrice} onChange={setStopPrice}/><Input label={t.target} value={target} onChange={setTarget}/></>;results=[[t.ratio,`1 : ${num(output.ratio)}`],[t.breakeven,`${num(output.breakeven)}%`]]}
  else if(tool==="drawdown"){fields=<><Input label={t.initial} value={initial} onChange={setInitial}/><Input label={t.current} value={current} onChange={setCurrent}/></>;results=[[t.drawdown,`${num(output.dd)}%`],[t.recovery,`${num(output.recovery)}%`]]}
  else {fields=<>{symbolField}<Input label={t.lots} value={lots} onChange={setLots}/><Input label={t.swapRate} value={swapRate} onChange={setSwapRate}/><Input label={t.nights} value={nights} onChange={setNights}/></>;results=[[t.swapTotal,money(output.swap)]]}
  const guide=guides[tool as keyof typeof guides];
  const detail=details[tool as keyof typeof details];
  return <section className={styles.page}><div className={styles.hero}><div className={styles.inner}><span className={styles.eyebrow}>{t.eyebrow}</span><h1>{t.title}</h1><div className={styles.heroGrid}><h2>{t.lead}</h2><p>{t.intro}</p></div></div></div><div className={styles.inner}><div className={styles.shell}><nav className={styles.tabs} aria-label={t.title}>{TOOLS.map(x=><button key={x.id} disabled={x.disabled} aria-disabled={x.disabled} className={`${tool===x.id?styles.active:""} ${x.disabled?styles.disabled:""}`} onClick={()=>!x.disabled&&setTool(x.id)}><ToolIcon id={x.id}/><span>{t[x.key]}</span>{x.disabled&&<small>{t.soon}</small>}</button>)}</nav><div className={styles.workspace}><div className={styles.form}><div className={styles.formHead}><div><div className={styles.sectionLabel}>01 — {t[TOOLS.find(x=>x.id===tool)!.key]}</div><h2>{t.inputTitle}</h2><p>{t.inputHint}</p></div><ToolIcon id={tool}/></div><div className={styles.fields}>{fields}</div></div><aside className={styles.results}><span>{t.calculate}</span><h3>{t.result}</h3>{results.map(([label,value],i)=><div className={styles.result} key={label}><small>{label}</small><strong className={i===0?styles.primary:""}>{value}</strong></div>)}<p>{t.disclaimer}</p></aside></div></div>{guide&&detail&&<section className={styles.tutorial}><div className={styles.tutorialHead}><span>02</span><div><h2>{t.tutorial}</h2><p>{t.tutorialIntro}</p></div></div><div className={styles.guideIntro}><span className={styles.guideIcon}><ToolIcon id={tool}/></span><div><small>{t.purpose}</small><h3>{t[TOOLS.find(x=>x.id===tool)!.key]}</h3><p>{detail.purpose}</p></div></div><ol>{guide.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><div><small>{t.step} {i+1}</small><p>{step}</p></div></li>)}</ol><div className={styles.formula}><small>{t.formula}</small><strong>{guide.formula}</strong></div><div className={styles.deepGuide}><article><small>{t.example}</small><p>{detail.example}</p></article><article><small>{t.interpretation}</small><p>{detail.interpretation}</p></article><aside><small>{t.practicalNote}</small><p>{detail.note}</p></aside></div></section>}</div></section>;
}
