import type { GuideArticleContent } from "../../guide-types";

export const bonusGuide: GuideArticleContent = {
  slug: "bonus",
  title: "Activating a Bonus",
  description:
    "Create a ROCO bonus account and activate promotional plans, including the 40% first-deposit reward.",
  lead: "To support its users and encourage activity, ROCO offers several promotional plans (bonuses). In this guide you will create a bonus account and review the conditions of each plan.",
  readingMinutes: 6,
  updatedAt: "2026-09-21",
  topics: ["Bonus", "First-Deposit Reward", "Loyalty Reward"],
  intro: [
    "Access to some bonuses is available only to users who joined ROCO with a referral code or link. If you intend to receive a bonus, enter your referral code before completing registration; adding a code after registration is not possible.",
  ],
  sections: [
    {
      id: "programs",
      heading: "ROCO bonus plans",
      table: {
        caption: "Active promotional plans",
        headers: ["Plan", "Condition", "Benefit"],
        rows: [
          [
            "40% first-deposit reward",
            "First deposit into a Lion account",
            "Up to $1,000; cannot be lost and its profit is always withdrawable",
          ],
          [
            "Motivational bonus and free coaching",
            "A $500 loss in a trading account",
            "A specialist calls to arrange a dedicated coaching session",
          ],
          ["Loyalty reward", "Trading 100 lots of EUR/USD", "$50 reward"],
        ],
      },
      callouts: [
        {
          variant: "note",
          title: "Bonus account leverage",
          body: [
            "The maximum leverage for the 40% first-deposit offer is 1:100. Profit generated by the bonus is always available for withdrawal.",
          ],
        },
      ],
    },
    {
      id: "steps",
      heading: "Steps to create a bonus account",
      lead: "To receive a bonus you must create a trading account of the Promotion type. Note that each user account is allowed to create only one bonus account.",
      steps: [
        {
          title: "Sign in to the Client Portal",
          body: "Sign in at my.rocobroker.com/login with the email and password you registered with, and open the hamburger menu in the top corner of the page.",
        },
        {
          title: "Go to the Accounts section",
          body: "In the menu, choose \"Accounts\". This page displays all of your accounts and their details.",
        },
        {
          title: "Create a new account",
          body: "Click the \"Create New Account\" button and select \"Real Account\" on the next page.",
        },
        {
          title: "Select the Promotion platform",
          body: "Open the \"Platform\" section and select \"MT5 - RocoBroker - Promotion\".",
        },
        {
          title: "Select the bonus type",
          body: "In the \"Account Type\" section, select the bonus you want. ROCO permanently offers \"BONUS 40%\" on a Lion account for every user's first deposit. If you joined with a referral code or link, other bonus options will likely be shown as well.",
        },
        {
          title: "Set leverage and accept the agreement",
          body: "Set the account's trading leverage. In the description section you can optionally enter a name for the account. Finally, check the \"User Agreement\" box and click the save button.",
        },
      ],
      callouts: [
        {
          variant: "warning",
          title: "You can receive a bonus only once",
          body: [
            "Each user account is allowed to create only one bonus trading account. Once the bonus account is approved and issued, no further bonus can be received; so review everything carefully and choose the most suitable bonus.",
          ],
        },
      ],
    },
    {
      id: "conditions",
      heading: "Important bonus conditions",
      bullets: [
        {
          text: "The 40% first-deposit reward is offered on a Lion account and its maximum payout is $1,000.",
        },
        {
          text: "This bonus cannot be lost, and any profit generated from it is always available for withdrawal.",
        },
        {
          text: "For the motivational bonus, if your trading account shows a $500 loss, ROCO specialists will contact you to arrange a dedicated coaching session.",
        },
        {
          text: "For the loyalty reward, after trading a total of 100 lots of EUR/USD, a $50 reward is added to your account.",
        },
      ],
    },
  ],
  reviewNotes: [
    "The plan conditions are taken from the promotions page of this site; however, how bonus options appear in the panel and the exact \"BONUS 40%\" label must be confirmed against the current panel version and the present terms of the promotions.",
    "Which bonuses are available only with a referral code is quoted from the previous guide, and the definitive list has not been independently confirmed.",
  ],
  references: [
    { label: "ROCO special offers page", href: "https://rocobroker.com/promotions" },
    { label: "Sign in to the Client Portal", href: "https://my.rocobroker.com/login" },
  ],
};
